#!/usr/bin/env bash
# Interactive .env builder for ccusage-mqtt.
#
# Prompts for the values you actually need to set per install / per instance.
# Everything else uses sane defaults — edit .env afterwards if you need to
# tweak polling cadences, mood thresholds, etc. (.env.example has the full list.)
#
# Re-running is safe: it asks before overwriting an existing .env.

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
    echo "$ENV_FILE already exists."
    read -r -p "Overwrite? [y/N] " ans
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing $ENV_FILE left in place."
        exit 0
    fi
fi

prompt() {
    # prompt <var-name> <human-label> <default>
    local var=$1 label=$2 default=$3 reply
    if [[ -n "$default" ]]; then
        read -r -p "${label} [${default}]: " reply
        reply=${reply:-$default}
    else
        read -r -p "${label}: " reply
    fi
    printf -v "$var" '%s' "$reply"
}

prompt_secret() {
    local var=$1 label=$2 reply
    read -r -s -p "${label} (leave blank if broker is unauthenticated): " reply
    echo
    printf -v "$var" '%s' "$reply"
}

echo "ccusage-mqtt setup"
echo "(everything not asked here takes a default — see .env.example for the full list)"
echo
echo "MQTT broker:"
prompt        MQTT_HOST        "  broker host" "homeassistant.local"
prompt        MQTT_PORT        "  broker port" "1883"
prompt        MQTT_USER        "  username"    ""
prompt_secret MQTT_PASS        "  password"

echo
echo "Per-instance identity (change these per instance for a multi-account setup):"
prompt        MQTT_DEVICE_NAME        "  HA device name"                            "Claude Code Usage"
prompt        ACCOUNT_NAME            "  Account label (e.g. 'work', 'personal')" "default"
prompt        CLAUDE_CONFIG_HOST_PATH "  Claude Code config dir on host"            "${HOME}/.claude"

if [[ ! -f "${CLAUDE_CONFIG_HOST_PATH}/.credentials.json" ]]; then
    echo
    echo "  WARNING: ${CLAUDE_CONFIG_HOST_PATH}/.credentials.json doesn't exist."
    echo "  Log in first with:  CLAUDE_CONFIG_DIR=${CLAUDE_CONFIG_HOST_PATH} claude login"
    echo "  (Continuing anyway — the container will exit with code 3 until you do.)"
fi

# When ACCOUNT_NAME is non-default, auto-suffix the MQTT topic and client ID
# so two instances on the same broker don't collide. User can still override
# both directly in .env after this script writes it.
ACCOUNT_SLUG=$(echo "$ACCOUNT_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_' | sed 's/__*/_/g; s/^_//; s/_$//')
if [[ -n "$ACCOUNT_SLUG" && "$ACCOUNT_SLUG" != "default" ]]; then
    MQTT_BASE_TOPIC="claude_code_usage_${ACCOUNT_SLUG}"
    MQTT_CLIENT_ID="ccusage-mqtt-${ACCOUNT_SLUG}"
else
    MQTT_BASE_TOPIC="claude_code_usage"
    MQTT_CLIENT_ID="ccusage-mqtt"
fi

# Container runs as this UID/GID so the read-only bind-mount of the host's
# Claude config dir (mode 0600 on the host) is readable inside the container.
USER_UID=$(id -u)
USER_GID=$(id -g)

echo
echo "Writing $ENV_FILE …"

umask 077  # ensure 0600 on create
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -Iseconds)
# Run \`./setup.sh\` to regenerate, or edit this file by hand.
# See .env.example for every supported variable + default.

# --- MQTT broker -----------------------------------------------------------
MQTT_HOST=${MQTT_HOST}
MQTT_PORT=${MQTT_PORT}
MQTT_USER=${MQTT_USER}
MQTT_PASS=${MQTT_PASS}
MQTT_DISCOVERY_PREFIX=homeassistant

# --- Per-instance identity -------------------------------------------------
MQTT_DEVICE_NAME=${MQTT_DEVICE_NAME}
MQTT_BASE_TOPIC=${MQTT_BASE_TOPIC}
MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
ACCOUNT_NAME=${ACCOUNT_NAME}

# --- Claude Code data sources ----------------------------------------------
CLAUDE_CONFIG_HOST_PATH=${CLAUDE_CONFIG_HOST_PATH}
CLAUDE_CREDENTIALS_PATH=/data/claude-projects/.credentials.json
CCUSAGE_PROJECTS_DIR=/data/claude-projects
ANTHROPIC_API_BASE=https://api.anthropic.com
PROBE_MODEL=claude-haiku-4-5-20251001

# --- Polling + tuning ------------------------------------------------------
HEADER_POLL_SEC=60
CCUSAGE_POLL_SEC=30
BURN_RATE_WINDOW_SEC=240
MOOD_IDLE_BELOW=0.10
MOOD_NORMAL_BELOW=0.20
MOOD_ACTIVE_BELOW=0.33
LOG_LEVEL=INFO

# --- Container runtime (docker compose user override) ----------------------
USER_UID=${USER_UID}
USER_GID=${USER_GID}
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE (mode 0600)"
echo
echo "Next steps:"
echo "  docker compose up -d --build"
echo "  docker compose logs -f"
