#!/usr/bin/env bash
# Interactive .env builder for ccusage-mqtt.
#
# Prompts for the broker settings (the only values you actually need to type)
# and writes the rest from defaults that match .env.example.
#
# Re-running is safe: it asks before overwriting an existing .env.

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
TEMPLATE=".env.example"

if [[ ! -f "$TEMPLATE" ]]; then
    echo "error: $TEMPLATE not found — run from the ccusage-mqtt repo root" >&2
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    echo "$ENV_FILE already exists."
    read -r -p "Overwrite? [y/N] " ans
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing $ENV_FILE left in place."
        exit 0
    fi
fi

prompt() {
    # prompt <var-name> <human-label> <default>
    local var=$1 label=$2 default=$3 reply
    if [[ -n "$default" ]]; then
        read -r -p "${label} [${default}]: " reply
        reply=${reply:-$default}
    else
        read -r -p "${label}: " reply
    fi
    printf -v "$var" '%s' "$reply"
}

prompt_secret() {
    local var=$1 label=$2 reply
    read -r -s -p "${label} (leave blank if broker is unauthenticated): " reply
    echo
    printf -v "$var" '%s' "$reply"
}

echo "ccusage-mqtt setup — MQTT broker settings"
echo "(everything else uses defaults from .env.example — edit later if needed)"
echo

prompt        MQTT_HOST       "MQTT broker host" "homeassistant.local"
prompt        MQTT_PORT       "MQTT broker port" "1883"
prompt        MQTT_USER       "MQTT username"    ""
prompt_secret MQTT_PASS       "MQTT password"

echo
echo "Writing $ENV_FILE …"

umask 077  # ensure 0600 on create
{
    # Header
    echo "# Generated by setup.sh on $(date -Iseconds)"
    echo
    # MQTT broker — the values we just collected
    echo "MQTT_HOST=${MQTT_HOST}"
    echo "MQTT_PORT=${MQTT_PORT}"
    echo "MQTT_USER=${MQTT_USER}"
    echo "MQTT_PASS=${MQTT_PASS}"
    # Everything else — copy non-MQTT lines from .env.example verbatim
    echo
    grep -vE '^(MQTT_HOST|MQTT_PORT|MQTT_USER|MQTT_PASS|# MQTT broker)' "$TEMPLATE"
} > "$ENV_FILE"

# Make sure it ended up 0600 (umask above should have done it, belt-and-braces).
chmod 600 "$ENV_FILE"

echo "✓ Wrote $ENV_FILE (mode 0600)"
echo
echo "Next steps:"
echo "  docker compose up -d --build"
echo "  docker compose logs -f"
