#!/usr/bin/env bash
# Interactive .env builder for ccusage-mqtt.
#
# Prompts for the broker settings (the only values you actually need to type)
# and writes the rest from defaults that match .env.example.
#
# Re-running is safe: it asks before overwriting an existing .env.

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
TEMPLATE=".env.example"

if [[ ! -f "$TEMPLATE" ]]; then
    echo "error: $TEMPLATE not found — run from the ccusage-mqtt repo root" >&2
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    echo "$ENV_FILE already exists."
    read -r -p "Overwrite? [y/N] " ans
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing $ENV_FILE left in place."
        exit 0
    fi
fi

prompt() {
    # prompt <var-name> <human-label> <default>
    local var=$1 label=$2 default=$3 reply
    if [[ -n "$default" ]]; then
        read -r -p "${label} [${default}]: " reply
        reply=${reply:-$default}
    else
        read -r -p "${label}: " reply
    fi
    printf -v "$var" '%s' "$reply"
}

prompt_secret() {
    local var=$1 label=$2 reply
    read -r -s -p "${label} (leave blank if broker is unauthenticated): " reply
    echo
    printf -v "$var" '%s' "$reply"
}

echo "ccusage-mqtt setup — MQTT broker settings"
echo "(everything else uses defaults from .env.example — edit later if needed)"
echo

prompt        MQTT_HOST        "MQTT broker host" "homeassistant.local"
prompt        MQTT_PORT        "MQTT broker port" "1883"
prompt        MQTT_USER        "MQTT username"    ""
prompt_secret MQTT_PASS        "MQTT password"

echo
echo "HA device identity (for multi-instance setups, change these per instance):"
prompt        MQTT_DEVICE_NAME "HA device name"   "Claude Code Usage"
prompt        ACCOUNT_NAME     "Account label (optional, e.g. 'work' or 'personal')" ""

# When ACCOUNT_NAME is set, auto-suffix the MQTT topic and client ID so two
# instances on the same broker don't collide. User can still override either.
if [[ -n "$ACCOUNT_NAME" ]]; then
    # Slugify: lower-case, strip non-alnum, collapse to underscores
    ACCOUNT_SLUG=$(echo "$ACCOUNT_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_' | sed 's/__*/_/g; s/^_//; s/_$//')
    MQTT_BASE_TOPIC="claude_code_usage_${ACCOUNT_SLUG}"
    MQTT_CLIENT_ID="ccusage-mqtt-${ACCOUNT_SLUG}"
else
    MQTT_BASE_TOPIC="claude_code_usage"
    MQTT_CLIENT_ID="ccusage-mqtt"
fi

# Container runs as this UID/GID so the read-only bind-mount of ~/.claude
# (mode 0600 on the host) is readable inside the container.
USER_UID=$(id -u)
USER_GID=$(id -g)

echo
echo "Writing $ENV_FILE …"

umask 077  # ensure 0600 on create
{
    # Header
    echo "# Generated by setup.sh on $(date -Iseconds)"
    echo
    # MQTT broker — the values we just collected
    echo "MQTT_HOST=${MQTT_HOST}"
    echo "MQTT_PORT=${MQTT_PORT}"
    echo "MQTT_USER=${MQTT_USER}"
    echo "MQTT_PASS=${MQTT_PASS}"
    echo "MQTT_CLIENT_ID=${MQTT_CLIENT_ID}"
    echo "MQTT_BASE_TOPIC=${MQTT_BASE_TOPIC}"
    echo "MQTT_DEVICE_NAME=${MQTT_DEVICE_NAME}"
    echo "ACCOUNT_NAME=${ACCOUNT_NAME}"
    echo
    # Match container UID/GID to host so the bind-mounted ~/.claude is readable.
    echo "USER_UID=${USER_UID}"
    echo "USER_GID=${USER_GID}"
    # Everything else — copy lines from .env.example verbatim, skipping the
    # ones we just wrote above and the header comment block.
    echo
    grep -vE '^(MQTT_HOST|MQTT_PORT|MQTT_USER|MQTT_PASS|MQTT_CLIENT_ID|MQTT_BASE_TOPIC|MQTT_DEVICE_NAME|ACCOUNT_NAME|USER_UID|USER_GID|# MQTT broker|# Friendly name|# Optional\.)' "$TEMPLATE"
} > "$ENV_FILE"

# Make sure it ended up 0600 (umask above should have done it, belt-and-braces).
chmod 600 "$ENV_FILE"

echo "✓ Wrote $ENV_FILE (mode 0600)"
echo
echo "Next steps:"
echo "  docker compose up -d --build"
echo "  docker compose logs -f"
